# Generated by Django 6.0.3 on 2026-03-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_path',
        ),
    ]
